---

- name: Command clear counters with prompt
  hosts: r1

  tasks:

    - name: Clear interface counters
      cli_command:
        command: clear counters e0/0
        prompt: 'Clear "show interface" counters on this interfaсe'
        answer: y

    - name: Clear interfaces counters in loop
      cli_command:
        command: clear counters {{ item }}
        prompt: 'Clear "show interface" counters on this interfaсe'
        answer: y
      loop: [e0/0, e0/1]
    
    - name: Few commands in loop 
      cli_command:
        command: "{{ item }}"
      loop: ["sh clock","sh ip int br"]
